@startuml
title DBモデリング2 課題1

entity "ユーザー" {
  ユーザーID
  ==
  名前
}

entity "ワークスペース" {
  ワークスペースID
  ==
  ワークスペース名
}

entity "ワークスペース参加ユーザー" {
  ワークスペースID
  ユーザーID
}

entity "チャンネル" {
  チャンネルID
  ワークスペースID[FK]
  ==
  チャンネル名
}

entity "チャンネル参加ユーザー" {
  チャンネルID
  ユーザーID
}

entity "スレッド" {
  スレッドID
  ==
  チャンネルID[FK]
}

entity "メッセージ" {
  メッセージID
  ==
  スレッドID[FK]
  ユーザーID[FK]
  メッセージタイプ(発言元・レス)
  発言内容
  発言日時
}

ユーザー ||-u-o{ ワークスペース参加ユーザー
ユーザー ||-u-o{ チャンネル参加ユーザー
ユーザー ||-r-o{ メッセージ

ワークスペース ||-r-o{ チャンネル
ワークスペース ||-d-o{ ワークスペース参加ユーザー

チャンネル ||-d-|{ チャンネル参加ユーザー
チャンネル ||--o{ スレッド

スレッド ||--o{ メッセージ

@enduml