@startuml
  entity "ユーザー" {
    ID
    ==
    名前
  }

  entity "記事" {
    ID
    ==
    ユーザーID[FK]
  }

  entity "記事履歴" {
    ID
    ==
    記事ID[FK]
    記事タイトル
    記事内容
    最新記事か？
  }

  ユーザー ||--o{ 記事
  記事 ||--|{ 記事履歴
@enduml