@startuml
  entity "ユーザー" {
    ID
    ==
    名前
  }

  entity "記事" {
    ID
    ==
    ユーザーID[FK]
  }

  entity "最新記事" {
    記事ID[FPK]
    記事履歴ID[FPK]
  }

  entity "記事履歴" {
    ID
    ==
    記事ID[FK]
    記事タイトル
    記事内容
  }

  ユーザー ||--o{ 記事
  記事 ||--|{ 記事履歴
  記事 ||--|{ 最新記事
  記事履歴 ||--|{ 最新記事
@enduml