@startuml
entity "リマインダー" {
  ID
  ==
  文面
  最終リマインド日時
}

entity "リマインドユーザー" {
  ID
  リマインダーID
  ==
  スラックのユーザーID
  完了したか？
}

entity "リマインド設定" {
  ID
  リマインダーID
  毎日
  x時間おき
  x日おき
  毎月x日
  月
  火
  水
  木
  金
  土
  日
}

リマインダー ||--|{ リマインドユーザー
リマインダー ||--|| リマインド設定
@enduml