@startuml
entity "ユーザー" {
  ユーザーID
  ==
  名前
}

entity "ディレクトリ" {
  ディレクトリID
  ==
  名前
}

entity "ディレクトリツリー" {
  ツリーID
  親ディレクトリID
  子ディレクトリID
}

entity "ドキュメント" {
  ドキュメントID
  所属ディレクトリID
  ==
  作成ユーザー
  作成日
}

entity "ドキュメントヒストリー" {
  ヒストリーID
  ドキュメントID
  ==
  更新ユーザー
  内容
  更新日
}

ディレクトリ }|-r-|{ ディレクトリツリー
ディレクトリ ||--|{ ドキュメント
ドキュメント ||-r-|{ドキュメントヒストリー
ドキュメント }|--|| ユーザー
ドキュメントヒストリー }|--|| ユーザー
@enduml