@startuml
  title 課題 2
  entity "メニュー" {
    メニューID
    ==
    名前
    値段
    種類(セット・単品)
  }

  entity "メニュー詳細" {
    メニュー内容ID
    メニューID[FK]
    寿司ID[FK]
  }

  entity "寿司" {
    寿司ID
    ==
    名前
  }

  entity "注文" {
    注文ID
    ==
    注文者名
    注文者電話番号
    合計額
    支払い済か？
    注文日時
  }

  entity "注文詳細" {
    注文詳細ID
    注文ID[FK]
    メニューID[FK]
    ==
    シャリ種類
    わさび有無
    注文個数
    小計額
  }

  メニュー詳細 }|--|| メニュー
  メニュー詳細 ||-r-|| 寿司
  注文 ||--|{ 注文詳細
  メニュー ||--|{ 注文詳細
@enduml
